// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyeywneynurtmwfsjyvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZXl3bmV5bnVydG13ZnNqeXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTE4MDAsImV4cCI6MjA3Mzg2NzgwMH0.fh2nbnyxIe-FT8LEGfr1U65LcaKTxj4-5lbhtvBGABE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});